app: # 应用基本配置
  env: local # 环境名称  可选值:local,prod
  port: 8080 # 服务监听端口号
  app_name: gin-app # 应用名称
  app_url: http://localhost # 应用域名
  timezone: Asia/Shanghai # 时区
  lang: en # 语言
  request_limit: 2 # 请求限制
  
admin: # 管理后台配置
  enable: true # 是否启用后台管理
  exclude_auth_path: /admin,/main/index,/manager/logout,/media/image_upload,/manager/manager_info # 管理后台,特殊的权限排除地址
  
log:
  level: info # 日志等级
  root_dir: ./storage/logs # 日志根目录
  filename: app.log # 日志文件名称
  request_filename: access.log # 请求日志文件
  format: json # 写入格式 可选json
  show_line: true # 是否显示调用行
  max_backups: 3 # 旧文件的最大个数
  max_size: 500 # 日志文件最大大小（MB）
  max_age: 28 # 旧文件的最大保留天数
  compress: true # 是否压缩

database:
  driver: mysql # 数据库驱动
  host: 172.18.0.12 # 域名
  port: 3306 # 端口号
  database: shalabing-gin # 数据库名称
  username: root # 用户名
  password: 123456 # 密码
  charset: utf8mb4 # 编码格式
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量
  log_mode: error # 日志级别 info
  enable_file_log_writer: true # 是否启用日志文件
  log_filename: sql.log # 日志文件名称

redis:
  host: 127.0.0.1 #宿主机ip,单机redis使用
  port: 6379
  db: 0
  password:
  addrs:
    - "172.18.0.5:7001"
    - "172.18.0.6:7002"
    - "172.18.0.7:7003"
    - "172.18.0.7:7004"
    - "172.18.0.9:7005"
    - "172.18.0.10:7006"
  pool_size: 10        # 连接池大小
  read_timeout: 5s     # 读取超时
  write_timeout: 5s    # 写入超时
  dial_timeout: 5s     # 连接超时

jwt:
  secret: 3Bde3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s
  jwt_ttl: 43200
  jwt_blacklist_grace_period: 43200 # redis过期时间,同时也是jwt过期时间
  refresh_grace_period: 1800

storage:
  default: local
  disks:
    local:
      root_dir: ./storage/app
      app_url: http://localhost:8080/storage
    ali_oss:
      access_key_id: access_key_id
      access_key_secret: access_key_secret
      bucket: bucket
      endpoint: endpoint
      is_ssl: true
      is_private: false
    qi_niu:
      access_key: access_key
      bucket: bucket
      domain: domain
      secret_key: secret_key
      is_ssl: true
      is_private: false

# 腾讯云sms短信发送
sms_tencent:
  secret_id                                                                  : xxx
  secret_key                                                                 : xxx
  # 指定接入地域域名(默认就近接入)
  endpoint                                                                  : sms.tencentcloudapi.com
  # 指定签名算法(默认为HmacSHA256)
  sign_method                                                                : TC3-HMAC-SHA256
  # 地域信息:https://cloud.tencent.com/document/api/382/52071#.E5.9C.B0.E5.9F.9F.E5.88.97.E8.A1.A8
  region                                                                    : ap-guangzhou
  # 短信应用ID: 短信SdkAppId在 [短信控制台] 添加应用后生成的实际SdkAppId，示例如1400006666
  sms_sdk_app_id                                                               : xxx
  # 短信签名内容: 使用 UTF-8 编码，必须填写已审核通过的签名
  sign_name                                                                  : xxx科技
  # 模板 ID: 必须填写已审核通过的模板 ID: 普通短信，验证码通用
  template_id_common                                                         : xxx
  #短信session_key, 后面还要加对应短信类型和电话号码,eg = sms.captcha115555555555
  session_key                                                               : sms:captcha
  # 验证码时间
  # 有效时间, 单位:秒
  captcha_expiring                                                          : 120
  # 间隔时间, 单位:秒
  captcha_interval                                                          : 60

queue:
  rabbitmq:
    host: 172.18.0.2
    port: 5672
    username: admin
    password: admin
    vhost: /
  kafka:
    brokers:
      - "172.18.0.18:9092" # Kafka broker地址 【配置hosts 172.18.0.18  kafka】
    topic: "my_topic"   # Kafka主题
    group_id: "unique_group_id_1" # 消费者组唯一【唯一组id就是点对点模式，相同的组就是广播模式或者发布订阅模式】

mongodb:
  uri: "mongodb://172.18.0.11:27017"
  username: admin
  password: 123456
  database: shalabing_gin  # 数据库名称,没用到

elasticsearch:
  addresses:
    - "http://172.18.0.14:9200"
  username: "elastic"
  password: "elastic"

clickhouse:
  host: "172.18.0.13"
  port: 9000
  username: "default"
  password: ""
  database: "shalabing_gin"
